//
// Created by shoam on 10/15/19.
//

#ifndef CPP_FIXED_POINT_SHOAMCO_FIXEDPOINTEXCEPTION_H
#define CPP_FIXED_POINT_SHOAMCO_FIXEDPOINTEXCEPTION_H

#endif //CPP_FIXED_POINT_SHOAMCO_FIXEDPOINTEXCEPTION_H
